### ISSUE TITLE
sending token name

### ISSUE THREAD

**Issue by halchester** [svested/js-interview#1]
In the README.md of the assignment, for frontend devs, it is required to send the JWT token to the API. But it does not specify with what name it should be sent to backend. It just says Authoriszation Header. The spacing is not allowed in headers when sending HTTP requests to server. I think you may need to specify with which name it has to send to backend. 

According to readme, the header is supposed to be
```
{ 
  "Authoriszation Header" : "someToken"
}
```
the header cannot contain spaces and so on, I've tried with `token` and also `Authorization` but nothing seems to be working. The spelling is also wrong.

**Comment by edisonzsq** [comment]
Hi @halchester, thanks for reaching out. The Authorization Bearer header is a common practice. I'm sure you can find the answer when you google how should authorization header looks like.

**Comment by halchester** [comment]
Hello @edisonzsq, my apologies, I thought the API needs particular name for receiving the token, Just making sure. Thanks!
